#!/bin/bash

# startup script
# chkconfig: 5 99 1
# description: startup script

# Licensed to Hortonworks, Inc. under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  Hortonworks, Inc. licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

SCRIPTS_PATH="/home/sandbox/start_scripts"
NAME="startup_script"
LOG="/var/log/startup_script.log"

source /etc/rc.d/init.d/functions

source $SCRIPTS_PATH/consts.sh

function restart() {
    date >> $LOG
    [ "$1" == "-r" ] && str="Stopping HDP..." || str="Starting HDP..."
    printf "%-70s\n" "$str" | tee -a $LOG
    bash $SCRIPTS_PATH/stop.sh >> $LOG 2>&1

    [ "$1" == "-r" ] && printf "%-70s\n" "Starting HDP..." | tee -a $LOG
    bash $SCRIPTS_PATH/start.sh >> $LOG 2>&1
}


case "$1" in
start)
    printf "%-50s\n" "Starting $NAME..." | tee -a $LOG
    
    mkdir /var/www/landing 2> /dev/null
    mount --bind /home/sandbox/sandbox-tutorials /var/www/landing

    echo "" > /etc/resolv.conf
    dhclient &

    /etc/init.d/mysqld start >> $LOG  #To make run.sh work (tutorials update)

    #bash $SCRIPTS_PATH/sandbox_component_versions.sh

    printf "%-50s\n" "Updating IP..." | tee -a $LOG
    bash $SCRIPTS_PATH/gen_hosts.sh
   
    printf "%-50s\n" "Updating sandbox..." | tee -a $LOG
    cd /home/sandbox/sandbox-shared

    sed -i 1i"nameserver 8.8.8.8" /etc/resolv.conf

    sudo -u sandbox git fetch >> /var/log/startup_script.log 2>&1
    sudo -u sandbox git checkout $BRANCH >> /var/log/startup_script.log 2>&1
    sudo -u sandbox git stash  >> /var/log/startup_script.log 2>&1
    pull_res=$(sudo -u sandbox git pull origin $BRANCH 2>> $LOG)
    echo $pull_res >> $LOG

    chown sandbox:sandbox -R /home/sandbox/sandbox-shared
    [ ! "$pull_res" = "Already up-to-date." ] && /home/sandbox/hue/build/env/bin/hue migrate  >> $LOG 2>&1
    sudo -u sandbox bash /home/sandbox/tutorials/tutorials_app/run/run.sh >> $LOG 2>&1

    echo "Starting HDP ..."
    bash $SCRIPTS_PATH/start.sh
    sudo -u hdfs hadoop dfsadmin -safemode leave
    
    printf "%-50s\n" "Starting sandbox..." | tee -a $LOG
    cd /home/sandbox/hue
    /etc/init.d/supervisord start >> $LOG 2>&1
    
    echo 0 > /proc/sys/kernel/hung_task_timeout_secs

    echo "You can now launch sandbox on http://$(getent ahosts `hostname` | awk '{print $1}' | head -n 1):8888/"
    stty -F /dev/tty1 -echo
    #open -c 1 -f -- python /home/sandbox/start_scripts/splash.py
;;
stop)
    date >> $LOG
    bash $SCRIPTS_PATH/stop.sh >> $LOG 2>&1
    /etc/init.d/supervisord stop >> $LOG 2>&1
;;

restart)
    restart -r
;;

*)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac
